import React, { useState, useEffect } from 'react';
import { motion } from 'motion/react';
import {
  FileCheck2,
  Download,
  ShieldAlert,
  ArrowLeft,
  Calendar,
  Clock,
  User,
  Phone,
  CheckCircle2,
  AlertTriangle,
  FileText,
  ThumbsDown,
  ThumbsUp,
  HelpCircle,
  ExternalLink,
  Printer
} from 'lucide-react';
import { CallSession } from '../types';
import { api } from '../services/api';
import { jsPDF } from 'jspdf';

interface EvidencePackPageProps {
  callId: string;
  onNavigate: (route: string) => void;
}

const timestampToSeconds = (timestamp: string) => {
  const [minutes, seconds] = timestamp.split(':').map(Number);
  return (minutes || 0) * 60 + (seconds || 0);
};

export const EvidencePackPage: React.FC<EvidencePackPageProps> = ({ callId, onNavigate }) => {
  const [call, setCall] = useState<CallSession | null>(null);
  const [feedback, setFeedback] = useState<'scam' | 'safe' | 'unsure' | null>(null);
  const [isGeneratingPdf, setIsGeneratingPdf] = useState(false);
  const [timelinePosition, setTimelinePosition] = useState(0);

  useEffect(() => {
    async function load() {
      const data = await api.getCallById(callId);
      if (data) {
        setCall(data);
        if (data.feedback) setFeedback(data.feedback);
      }
    }
    load();
  }, [callId]);

  const handleFeedback = async (type: 'scam' | 'safe' | 'unsure') => {
    setFeedback(type);
    if (call) {
      await api.sendFeedback(call.id, type);
    }
  };

  const handleDownloadComplaint = () => {
    setIsGeneratingPdf(true);

    try {
      const doc = new jsPDF({
        orientation: 'portrait',
        unit: 'mm',
        format: 'a4',
      });

      const pageWidth = doc.internal.pageSize.getWidth();
      const margin = 14;
      let y = 18;

      // Header Banner
      doc.setFillColor(15, 23, 42); // dark slate
      doc.rect(margin, y, pageWidth - 2 * margin, 24, 'F');

      doc.setTextColor(255, 255, 255);
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(13);
      doc.text('NATIONAL CYBER CRIME REPORTING PORTAL (HELPLINE: 1930)', margin + 4, y + 8);

      doc.setFont('helvetica', 'normal');
      doc.setFontSize(9);
      doc.setTextColor(203, 213, 225);
      doc.text('I4C Coercive Telephony Evidence Dossier | Generated by Kaaval Scam Call Shield', margin + 4, y + 14);
      doc.text(`Case Ref: KAAVAL-CYBER-${call?.id?.toUpperCase() || '1049'} | Date: ${new Date().toLocaleString()}`, margin + 4, y + 19);

      y += 30;

      // Section 1: Metadata
      doc.setTextColor(15, 23, 42);
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(11);
      doc.text('1. INCIDENT & PARTY DETAILS', margin, y);
      y += 5;

      doc.setFont('helvetica', 'normal');
      doc.setFontSize(9);
      doc.setTextColor(51, 65, 85);

      const metadataLines = [
        `Protected Individual : ${call?.elderName || 'Kavitha Ramaswamy (68 Yrs)'}`,
        `Registered Phone     : ${call?.elderPhone || '+91 94441 90212'} (Redacted PII Protected)`,
        `Suspected Caller     : ${call?.callerLabel || 'Impersonating Mumbai Cyber Crime Cell'}`,
        `Originating Number   : ${call?.callerNumber || '+91 98201 44521'}`,
        `Call Duration        : ${call?.durationSeconds || 142} seconds`,
        `Risk Severity Score  : ${call?.riskScore || 92} / 100 (${(call?.riskScore || 92) >= 65 ? 'CRITICAL SCAM COERCION' : 'SUSPICIOUS'})`,
      ];

      metadataLines.forEach((line) => {
        doc.text(line, margin + 2, y);
        y += 4.5;
      });

      y += 4;

      // Section 2: Flagged Tactics & Quotes
      doc.setTextColor(15, 23, 42);
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(11);
      doc.text('2. EXTRACTED COERCIVE TACTICS & VERBATIM EVIDENCE', margin, y);
      y += 6;

      doc.setFont('helvetica', 'normal');
      doc.setFontSize(9);

      if (call?.detectedTactics && call.detectedTactics.length > 0) {
        call.detectedTactics.forEach((t, i) => {
          if (y > 260) {
            doc.addPage();
            y = 20;
          }
          doc.setFont('helvetica', 'bold');
          doc.setTextColor(185, 28, 28);
          doc.text(`[${i + 1}] ${t.name.toUpperCase()} (Severity: ${t.severity.toUpperCase()}, Confidence: ${(t.confidence * 100).toFixed(0)}%)`, margin + 2, y);
          y += 4.5;

          doc.setFont('helvetica', 'italic');
          doc.setTextColor(51, 65, 85);
          const quoteLines = doc.splitTextToSize(`Verbatim Quote: "${t.quote}"`, pageWidth - 2 * margin - 6);
          doc.text(quoteLines, margin + 4, y);
          y += quoteLines.length * 4.5 + 2;
        });
      } else {
        doc.text('No coercive tactics flagged.', margin + 2, y);
        y += 6;
      }

      y += 3;

      // Section 3: Call Transcript
      if (y > 240) {
        doc.addPage();
        y = 20;
      }

      doc.setTextColor(15, 23, 42);
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(11);
      doc.text('3. VERBATIM CALL TRANSCRIPTION LOG', margin, y);
      y += 6;

      doc.setFont('helvetica', 'normal');
      doc.setFontSize(8.5);
      doc.setTextColor(30, 41, 59);

      if (call?.transcript && call.transcript.length > 0) {
        call.transcript.forEach((t) => {
          if (y > 270) {
            doc.addPage();
            y = 20;
          }
          const speakerLine = `[${t.timestamp}] ${t.speaker.toUpperCase()}: ${t.text}`;
          const splitLines = doc.splitTextToSize(speakerLine, pageWidth - 2 * margin - 4);
          doc.text(splitLines, margin + 2, y);
          y += splitLines.length * 4 + 1.5;
        });
      }

      y += 6;

      // Section 4: Legal Directives & Section 65B Certificate
      if (y > 240) {
        doc.addPage();
        y = 20;
      }

      doc.setTextColor(15, 23, 42);
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(10);
      doc.text('4. LAW ENFORCEMENT & BANK RECOVERY DIRECTIVES', margin, y);
      y += 5;

      doc.setFont('helvetica', 'normal');
      doc.setFontSize(8);
      doc.setTextColor(71, 85, 105);

      const directives = [
        '[✓] Submit online complaint at https://cybercrime.gov.in or dial National Helpline 1930 immediately.',
        '[✓] Present this dossier to branch manager to freeze outgoing IMPS/NEFT/UPI transactions.',
        '[✓] Report originating phone number to DoT Chakshu Portal (sancharsaathi.gov.in/sfc).',
        '[✓] Certified Electronic Record under Section 65B of the Indian Evidence Act, 1872.',
      ];

      directives.forEach((d) => {
        doc.text(d, margin + 2, y);
        y += 4;
      });

      // Save PDF
      doc.save(`Kaaval_Cybercrime_Complaint_${call?.id || '1049'}.pdf`);
    } catch (err) {
      console.error('PDF generation error', err);
    } finally {
      setIsGeneratingPdf(false);
    }
  };

  if (!call) {
    return (
      <div className="min-h-[calc(100vh-4rem)] flex items-center justify-center bg-[#0B0F14] text-white">
        <div className="animate-spin w-8 h-8 border-2 border-[#5B8FFF] border-t-transparent rounded-full" />
      </div>
    );
  }

  const isHigh = call.riskScore > 65;
  const activeTactic = [...call.detectedTactics].reverse().find((tactic) => timestampToSeconds(tactic.timestamp || '00:00') <= timelinePosition);

  return (
    <div className="min-h-[calc(100vh-4rem)] bg-[#0B0F14] py-8 px-4 text-[#E5E7EB] sm:px-6 lg:px-8">
      <div className="max-w-6xl mx-auto space-y-6">
        {/* Breadcrumb Navigation */}
        <div className="flex items-center gap-2 text-xs font-mono text-[#9CA3AF]">
          <button
            type="button"
            onClick={() => onNavigate('/demo/family')}
            className="hover:text-white flex items-center gap-1"
          >
            <ArrowLeft className="w-3.5 h-3.5" />
            <span>Dashboard</span>
          </button>
          <span>/</span>
          <span>Calls</span>
          <span>/</span>
          <span className="text-[#5B8FFF] font-bold">Call #{call.id}</span>
        </div>

        {/* Header Title Card */}
        <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 p-6 sm:p-8 rounded-3xl bg-[#121821] border border-[#1E293B]">
          <div className="space-y-1">
            <div className="flex items-center gap-2.5">
              <span className="px-2.5 py-0.5 rounded-full bg-red-500/15 border border-red-500/30 text-red-400 font-mono text-xs font-semibold">
                EVIDENCE PACK GENERATED
              </span>
              <span className="text-xs font-mono text-[#9CA3AF]">{call.startTime}</span>
            </div>
            <h1 className="text-2xl sm:text-3xl font-bold text-white tracking-tight">
              Call Summary & Legal Complaint Dossier
            </h1>
            <p className="text-xs sm:text-sm text-[#9CA3AF]">
              Forensic audit for National Cyber Crime Portal (1930) and Banking Ombudsman dispute.
            </p>
          </div>

          <div className="flex items-center gap-3">
            <button
              type="button"
              onClick={handleDownloadComplaint}
              disabled={isGeneratingPdf}
              className="px-5 py-3 rounded-xl bg-[#5B8FFF] hover:bg-[#4A7CEB] text-white text-xs font-bold tracking-wider flex items-center gap-2 shadow-lg shadow-[#5B8FFF]/25 transition-all active:scale-95 cursor-pointer"
            >
              <Download className="w-4 h-4" />
              <span>{isGeneratingPdf ? 'Generating...' : 'Download Complaint Pack (PDF)'}</span>
            </button>
          </div>
        </div>

        {/* Two-Column Layout */}
        <div className="grid grid-cols-1 items-start gap-6 lg:grid-cols-12">
          {/* Left Column (Metadata + Transcript + Tactic timeline) */}
          <div className="space-y-6 rounded-lg bg-[#F4F1EA] p-5 text-[#1D252D] shadow-[0_20px_60px_rgba(0,0,0,0.28)] sm:p-8 lg:col-span-8">
            <div className="border-b border-[#C8C0B2] pb-5 font-serif">
              <p className="font-mono text-[11px] uppercase tracking-[0.08em] text-[#5B6570]">Auto-generated summary</p>
              <p className="mt-2 text-sm leading-6 text-[#4A535D]">Verify details before filing at cybercrime.gov.in or via the 1930 helpline.</p>
            </div>
            {/* Call Metadata Grid */}
            <div className="grid grid-cols-2 sm:grid-cols-4 gap-3">
              <div className="rounded border border-[#D7D0C3] bg-[#FFFDF8] p-4">
                <span className="text-[10px] font-mono text-[#9CA3AF] uppercase block">Protected Elder</span>
                <p className="font-semibold text-white text-sm mt-1 truncate">{call.elderName}</p>
                <span className="text-[11px] font-mono text-[#9CA3AF]">{call.elderPhone}</span>
              </div>

              <div className="rounded border border-[#D7D0C3] bg-[#FFFDF8] p-4">
                <span className="text-[10px] font-mono text-[#9CA3AF] uppercase block">Suspect Caller</span>
                <p className="font-semibold text-red-300 text-sm mt-1 truncate">{call.callerLabel}</p>
                <span className="text-[11px] font-mono text-[#9CA3AF]">{call.callerNumber}</span>
              </div>

              <div className="rounded border border-[#D7D0C3] bg-[#FFFDF8] p-4">
                <span className="text-[10px] font-mono text-[#9CA3AF] uppercase block">Call Duration</span>
                <p className="font-semibold text-white text-sm mt-1">{call.durationSeconds} seconds</p>
                <span className="text-[11px] font-mono text-emerald-400">Archived Volatile</span>
              </div>

              <div className="rounded border border-[#D7D0C3] bg-[#FFFDF8] p-4">
                <span className="text-[10px] font-mono text-[#9CA3AF] uppercase block">Threat Score</span>
                <p className={`font-mono font-bold text-xl mt-0.5 ${isHigh ? 'text-red-400' : 'text-emerald-400'}`}>
                  {call.riskScore}/100
                </p>
                <span className="text-[10px] font-mono text-red-400 uppercase">Extreme Risk</span>
              </div>
            </div>

            {/* Tactic Timeline */}
            <div className="space-y-4 rounded border border-[#D7D0C3] bg-[#FFFDF8] p-6">
              <div className="flex items-center justify-between pb-3 border-b border-[#1E293B]">
                <h3 className="flex items-center gap-2 font-serif text-xl font-bold text-[#1D252D]">
                  <ShieldAlert className="h-4 w-4 text-[#A91524]" />
                  <span>Detected tactics</span>
                </h3>
                <span className="text-xs font-mono text-[#9CA3AF]">{call.detectedTactics.length} markers</span>
              </div>

              <div className="space-y-3">
                {call.detectedTactics.map((tac, idx) => (
                  <div key={idx} className={`flex items-start gap-3 rounded border p-3.5 ${activeTactic?.id === tac.id ? 'border-[#A91524] bg-[#FFF0EE]' : 'border-[#D7D0C3] bg-[#F4F1EA]'}`}>
                    <span className="px-2 py-0.5 rounded bg-red-500/20 text-red-300 font-mono text-xs font-bold shrink-0">
                      {tac.timestamp || `00:${15 * (idx + 1)}`}
                    </span>
                    <div className="space-y-1">
                      <div className="flex items-center gap-2">
                        <span className="text-sm font-bold text-white">{tac.name}</span>
                        <span className="text-[10px] font-mono text-amber-400">
                          ({(tac.confidence * 100).toFixed(0)}% AI confidence)
                        </span>
                      </div>
                      <p className="text-xs text-red-300 italic">&quot;{tac.quote}&quot;</p>
                      <p className="text-[11px] text-[#9CA3AF]">{tac.description}</p>
                    </div>
                  </div>
                ))}
              </div>
            </div>

            {/* Full Verbatim Transcript Excerpt */}
            <div className="space-y-4 rounded border border-[#D7D0C3] bg-[#FFFDF8] p-6">
              <div className="flex items-center justify-between pb-3 border-b border-[#1E293B]">
                <h3 className="flex items-center gap-2 font-serif text-xl font-bold text-[#1D252D]">
                  <FileText className="w-4 h-4 text-[#5B8FFF]" />
                  <span>Verbatim Speech-to-Text Transcript</span>
                </h3>
                <span className="text-xs font-mono text-[#9CA3AF]">Whisper Audio Engine</span>
              </div>

              <div className="max-h-72 space-y-3 overflow-y-auto pr-2">
                {call.transcript.map((chunk, idx) => (
                  <div key={idx} className="text-xs space-y-0.5">
                    <div className="flex items-baseline gap-2">
                      <span className="font-mono text-[#9CA3AF] text-[11px]">[{chunk.timestamp}]</span>
                      <span
                        className={`font-semibold ${
                          chunk.speaker === 'caller' ? 'text-red-400' : 'text-emerald-400'
                        }`}
                      >
                        {chunk.speaker === 'caller' ? 'Suspect (Caller)' : 'Victim (Elder)'}:
                      </span>
                    </div>
                    <p className="pl-12 font-serif text-base leading-7 text-[#1D252D]">{chunk.text}</p>
                    {chunk.translation && (
                      <p className="text-[#9CA3AF] pl-12 text-[11px] italic">{chunk.translation}</p>
                    )}
                  </div>
                ))}
              </div>
              <div className="border-t border-[#D7D0C3] pt-4">
                <div className="flex items-center justify-between font-mono text-xs text-[#5B6570]"><span>Transcript timeline</span><span>{Math.floor(timelinePosition / 60).toString().padStart(2, '0')}:{(timelinePosition % 60).toString().padStart(2, '0')}</span></div>
                <input aria-label="Scrub transcript timeline" type="range" min="0" max={Math.max(call.durationSeconds, 1)} value={timelinePosition} onChange={(event) => setTimelinePosition(Number(event.target.value))} className="mt-3 w-full accent-[#A91524]" />
                <p className="mt-2 text-sm text-[#5B6570]">{activeTactic ? `At this point: ${activeTactic.name}` : 'Drag to inspect the call timeline.'}</p>
              </div>
            </div>
          </div>

          {/* Right Column (Evidence Checklist + Next Steps + Feedback) */}
          <div className="space-y-6 lg:sticky lg:top-24 lg:col-span-4">
            {/* Evidence Pack Section Checklist */}
            <div className="p-6 sm:p-7 rounded-3xl bg-[#121821] border border-[#1E293B] space-y-5">
              <div className="flex items-center gap-2.5 pb-3 border-b border-[#1E293B]">
                <FileCheck2 className="w-5 h-5 text-emerald-400" />
                <h3 className="text-base font-bold text-white">Verified Evidence Checklist</h3>
              </div>

              <div className="space-y-3 text-sm">
                <div className="flex items-start gap-3 p-3 rounded-xl bg-[#0B0F14] border border-[#1E293B]">
                  <CheckCircle2 className="w-4 h-4 text-emerald-400 shrink-0 mt-0.5" />
                  <div>
                    <span className="font-semibold text-white">Full Speech Transcript</span>
                    <p className="text-xs text-[#9CA3AF]">Synchronized timestamps and caller tone classification.</p>
                  </div>
                </div>

                <div className="flex items-start gap-3 p-3 rounded-xl bg-[#0B0F14] border border-[#1E293B]">
                  <CheckCircle2 className="w-4 h-4 text-emerald-400 shrink-0 mt-0.5" />
                  <div>
                    <span className="font-semibold text-white">3 Identified Coercion Tactics</span>
                    <p className="text-xs text-[#9CA3AF]">Authority impersonation, urgent arrest threat, secrecy demand.</p>
                  </div>
                </div>

                <div className="flex items-start gap-3 p-3 rounded-xl bg-[#0B0F14] border border-[#1E293B]">
                  <CheckCircle2 className="w-4 h-4 text-emerald-400 shrink-0 mt-0.5" />
                  <div>
                    <span className="font-semibold text-white">Automated Risk Score ({call.riskScore}/100)</span>
                    <p className="text-xs text-[#9CA3AF]">Calculated against Indian national scam taxonomy.</p>
                  </div>
                </div>

                <div className="flex items-start gap-3 p-3 rounded-xl bg-[#0B0F14] border border-[#1E293B]">
                  <CheckCircle2 className="w-4 h-4 text-emerald-400 shrink-0 mt-0.5" />
                  <div>
                    <span className="font-semibold text-white">Recommended Next Steps</span>
                    <p className="text-xs text-[#9CA3AF]">Pre-filled cyber complaint format ready for police submission.</p>
                  </div>
                </div>
              </div>

              <button
                type="button"
                onClick={handleDownloadComplaint}
                className="w-full py-3.5 rounded-xl bg-[#5B8FFF] hover:bg-[#4A7CEB] text-white font-semibold text-sm flex items-center justify-center gap-2 shadow-lg shadow-[#5B8FFF]/25 transition-all active:scale-95"
              >
                <Download className="w-4 h-4" />
                <span>Export Formal Complaint PDF</span>
              </button>
            </div>

            {/* Recommended Next Steps */}
            <div className="p-6 sm:p-7 rounded-3xl bg-[#121821] border border-[#1E293B] space-y-4">
              <h3 className="text-sm font-bold text-white uppercase tracking-wider flex items-center gap-2">
                <AlertTriangle className="w-4 h-4 text-amber-400" />
                <span>Immediate Protective Steps</span>
              </h3>

              <div className="space-y-3 text-xs">
                <div className="p-3 rounded-xl bg-[#0B0F14] border border-[#1E293B]">
                  <p className="font-semibold text-white">1. Call National Cyber Helpline 1930</p>
                  <p className="text-[#9CA3AF] mt-0.5">Report financial fraud immediately within the golden hour to freeze transfers.</p>
                </div>

                <div className="p-3 rounded-xl bg-[#0B0F14] border border-[#1E293B]">
                  <p className="font-semibold text-white">2. Block Number on DoT Sanchar Saathi</p>
                  <p className="text-[#9CA3AF] mt-0.5">Submit suspect caller info to national telecom blacklist.</p>
                </div>

                <div className="p-3 rounded-xl bg-[#0B0F14] border border-[#1E293B]">
                  <p className="font-semibold text-white">3. Remind Parent</p>
                  <p className="text-[#9CA3AF] mt-0.5">Reassure mother that police never conduct video arrests or demand bank OTPs.</p>
                </div>
              </div>
            </div>

            {/* Feedback Buttons: Model Improvement */}
            <div className="p-6 rounded-3xl bg-[#121821] border border-[#1E293B] space-y-3">
              <span className="text-xs font-mono text-[#9CA3AF] uppercase block">Model Training Feedback</span>
              <p className="text-xs text-white">Help train Kaaval&apos;s classifier for elder dialect accuracy:</p>

              <div className="grid grid-cols-3 gap-2 pt-1">
                <button
                  type="button"
                  onClick={() => handleFeedback('scam')}
                  className={`py-2 px-3 rounded-xl text-xs font-semibold flex items-center justify-center gap-1.5 border transition-all ${
                    feedback === 'scam'
                      ? 'bg-red-500 text-white border-red-500 shadow-md shadow-red-900/30'
                      : 'bg-[#0B0F14] hover:bg-[#1A222F] text-red-400 border-[#1E293B]'
                  }`}
                >
                  <ThumbsDown className="w-3.5 h-3.5" />
                  <span>Mark as Scam</span>
                </button>

                <button
                  type="button"
                  onClick={() => handleFeedback('safe')}
                  className={`py-2 px-3 rounded-xl text-xs font-semibold flex items-center justify-center gap-1.5 border transition-all ${
                    feedback === 'safe'
                      ? 'bg-emerald-600 text-white border-emerald-600 shadow-md shadow-emerald-900/30'
                      : 'bg-[#0B0F14] hover:bg-[#1A222F] text-emerald-400 border-[#1E293B]'
                  }`}
                >
                  <ThumbsUp className="w-3.5 h-3.5" />
                  <span>Mark as Safe</span>
                </button>

                <button
                  type="button"
                  onClick={() => handleFeedback('unsure')}
                  className={`py-2 px-3 rounded-xl text-xs font-semibold flex items-center justify-center gap-1.5 border transition-all ${
                    feedback === 'unsure'
                      ? 'bg-amber-500 text-black border-amber-500 shadow-md'
                      : 'bg-[#0B0F14] hover:bg-[#1A222F] text-amber-400 border-[#1E293B]'
                  }`}
                >
                  <HelpCircle className="w-3.5 h-3.5" />
                  <span>Not Sure</span>
                </button>
              </div>

              {feedback && (
                <p className="text-[11px] font-mono text-emerald-400 pt-1 text-center">
                  ✓ Feedback logged to local AML feedback dataset.
                </p>
              )}
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};
